=== mshanthiswaroop/66G2_NODE_JS/GreenCampusXML/greencampus.dtd
<!ELEMENT GreenCampus
    (Resources, ConsumptionRecords, SustainabilityMetrics)>

<!ATTLIST GreenCampus
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

<!ELEMENT Resources (Resource+)>
<!ELEMENT Resource (Name, Type, Quantity)>
<!ATTLIST Resource id ID #REQUIRED>

<!ELEMENT Name (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>

<!ELEMENT ConsumptionRecords (Record+)>
<!ELEMENT Record (ResourceName, Consumption, RecordDate)>
<!ATTLIST Record id ID #REQUIRED>

<!ELEMENT ResourceName (#PCDATA)>
<!ELEMENT Consumption (#PCDATA)>
<!ELEMENT RecordDate (#PCDATA)>

<!ELEMENT SustainabilityMetrics (Metric+)>
<!ELEMENT Metric (Name, Value, Unit)>
<!ATTLIST Metric id ID #REQUIRED>

<!ELEMENT Value (#PCDATA)>
<!ELEMENT Unit (#PCDATA)>

=== mshanthiswaroop/66G2_NODE_JS/GreenCampusXML/greencampus.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE GreenCampus SYSTEM "greencampus.dtd">

<GreenCampus
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="greencampus.xsd">

    <Resources>
        <Resource id="R1">
            <Name>Solar Panels</Name>
            <Type>Energy</Type>
            <Quantity>50</Quantity>
        </Resource>
        <Resource id="R2">
            <Name>Water Tanks</Name>
            <Type>Water</Type>
            <Quantity>10</Quantity>
        </Resource>
    </Resources>

    <ConsumptionRecords>
        <Record id="C1">
            <ResourceName>Electricity</ResourceName>
            <Consumption>1250.5</Consumption>
            <RecordDate>2026-10-26</RecordDate>
        </Record>
    </ConsumptionRecords>

    <SustainabilityMetrics>
        <Metric id="M1">
            <Name>Recycling Rate</Name>
            <Value>74</Value>
            <Unit>Percent</Unit>
        </Metric>
    </SustainabilityMetrics>

</GreenCampus>
